# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.nos
canonical: https://interop.esante.gouv.fr/ig/nos
name: NOS
title: Nomenclatures des objets de santé (NOS)
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
description: Les nomenclatures des objets de Sante
version: 1.4.0
date: 2024-08
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: trial-use

parameters:
    shownav: 'true'
    path-temp : /tmp
    path-resource:
        - input/NOS/

pages:
    index.xml:
        title: Accueil
    nos.md:
        title : NOS     
        NOS_MigrationNOSversSMTT0_01_PresDesNOSetSMT.md:
            title :   Présentation
        NOS_MigrationNOSversSMTT0_10_QuestCeQuneTRE.md:
            title :   TRE (définition)
        NOS_MigrationNOSversSMTT0_11_ProprietesDesTRE.md:
            title :   TRE (Propriété)
        NOS_MigrationNOSversSMTT0_12_CycleDeVieDesTRE.md:
            title :   TRE (Cycle de vie)
        NOS_MigrationNOSversSMTT0_20_QuestCeQunJDV.md:
            title :   JDV (définition)
        NOS_MigrationNOSversSMTT0_23_CycleDeVieDesJDV.md:
            title :   JDV (Cycle de vie)
        NOS_MigrationNOSversSMTT0_50_Publication.md:
            title :   Publication
        NOS_MigrationNOSversSMTT0_51_NommageDesNOS.md:
            title :   Nommage
        NOS_MigrationNOSversSMTT0_02_LaMigration.md:
            title :   Migration      
        NOS_MiseEnQualite_RepriseDesLibellesDesJDV.md:
            title :   Reprise des libellés     
        NOS_MiseEnQualiteCorrectionDuMappingNOSversFhir.md:
            title :   Mapping NOS to FHIR                                   
    tre.xml:
        title :  Terminologies   
    telechargement-tre.xml:
        title :  Terminologies      
    jdv.xml:
        title :  Jeux de valeurs 
    telechargement-jdv.xml:
        title :  Jeux de valeurs            
    ass.xml:
        title :  Association 
    namingSystem.xml:
        title :  namingSystem         
    telechargement-ass.xml:
        title :  Association             
    autres_ressources.md:
        title: Autres Ressources
        telechargementNos.md:
            title :   téléchargement (NOS)           
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html         
    Terminologies  : tre.html
    Jeux de valeurs  : jdv.html
    Association  : ass.html       

    Ressources:
        Téléchargement (NOS) : telechargementNos.html
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html
